name: QA

on: pull_request

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Use PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer
    # - name: Install dependencies
    #   run: |
    #     npm ci
    # - name: Run QA
    #   run: |
    #     npm run qa
    # - name: Run build
    #   run: |
    #     npm run build
